name: rbac

services:
  backend:
    image: rbac-image
    container_name: rbac-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    env_file:
      - .env
